config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  post '/callback' => 'linebot#callback'
  post '/send_line_message', to: 'linebot#send_message'

  get '/users', to: 'users#show', as: 'users'
  get '/users/edit', to: 'users#edit', as: 'users_edit'
  get 'recommend_routines', to: 'users#recommend_routine'

  post 'routines', to: 'routines#index'

  resources :users, only: %i[new create update]
  resources :routines, only: %i[index show]
  resources :sleep_records, only: %i[index new create]
end

app/models/sleep_record.rb
# frozen_string_literal: true

class SleepRecord < ApplicationRecord
  belongs_to :user
  belongs_to :routine, optional: true

  validates :user_id, presence: true

  enum morning_condition: { good: 0, normal: 1, bad: 2 }

  CONDITION_MAPPING = {
    'good' => '良い',
    'normal' => '普通',
    'bad' => '悪い'
  }.freeze

  def self.record_condition(user_id, received_text)
    condition = received_text
    record = find_by(user_id: user_id, record_date: Date.today, morning_condition: nil)

    if record
      if morning_conditions.keys.include?(condition)
        record.update(morning_condition: morning_conditions[condition], wake_up_time: Time.current)
        '調子を記録しました。今日も一日頑張りましょう！'
      end
    else
      '調子は記録済みです！今日も一日頑張りましょう！'
    end
  end

  def self.fetch_records(user_id, start_date, end_date)
    where(user_id: user_id)
      .where(record_date: start_date..end_date)
      .order(record_date: :desc)
  end

  def self.determine_date_range(params)
    year, month = if params['month(1i)'].present? && params['month(2i)'].present?
                    [params['month(1i)'].to_i, params['month(2i)'].to_i]
                  else
                    [Date.today.year, Date.today.month]
                  end
    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month
    [start_date, end_date, year, month]
  end

  def self.grouped_by_date(year, month, user_id)
    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month
    where(user_id: user_id, record_date: start_date..end_date)
      .order('record_date DESC')
      .group_by(&:record_date)
  end

  def user_routines
    user.user_routines.where(choose_date: record_date)
  end
end

app/controllers/sleep_records_controller.rb
# frozen_string_literal: true

class SleepRecordsController < ApplicationController
  before_action :require_login
  before_action :set_user, only: %i[new create]
  before_action :set_date

  def index
    @sleep_records = SleepRecord.fetch_records(current_user.id, @start_date, @end_date)
    @last_record = current_user.bedtime
  end

  private

  def set_user
    @user = current_user
  end

  def set_date
    @start_date, @end_date, @year, @month = SleepRecord.determine_date_range(params)
  end
end

app/helpers/sleep_records_helper.rb
# frozen_string_literal: true

module SleepRecordsHelper
end

app/views/sleep_records/index.html.erb
<%= flash_message(:success) %>

<div class="container mx-auto text-gray-700 p-4 flex justify-center">
<div class="w-auto">
  <h1 class="text-4xl my-10 text-center">睡眠の記録</h1>
  <% if @last_record %>
    <div class="text-xl md:text-3xl mb-10 text-center flex justify-center">
      <div class="mr-10">
      <p>目標の就寝時間: <%= current_user.bedtime&.in_time_zone("Tokyo").strftime("%H:%M") %></p>
      </div>
      <p>目標の起床時間: <%= current_user.notification_time&.in_time_zone("Tokyo").strftime("%H:%M") %></p>
    </div>
  <% end %>
  
  <%= form_with url: sleep_records_path, method: :get, local: true, class: "text-center mb-10" do |f| %>
    <%= f.date_select :month, { discard_day: true, selected: Date.new(@year, @month, 1) }, class: "border border-black bg-white text-2xl" %>
    <%= f.submit "フィルター", class: "btn btn-primary ml-5 md:ml-10" %>
  <% end %>
  
  <table class="text-2xl bg-white rounded-md shadow overflow-hidden mx-auto">
    <thead class="bg-gray-100">
      <tr>
        <th class="md:px-10 py-4">日付</th>
        <th class="md:px-10 py-4">朝の記録</th>
        <th class="md:px-10 py-4">調子</th>
      </tr>
    </thead>
    <tbody>
      <% @sleep_records.each do |record| %>
        <tr>
          <td class="border px-4 py-2"><%= format_date_for_device(record.record_date) %></td>
          <td class="border px-4 py-2"><%= record.wake_up_time ? record.wake_up_time.in_time_zone("Tokyo").strftime("%H:%M") : '未記録' %></td>
          <td class="border px-4 py-2">
          <% if record.morning_condition %>
            <%= ['良い', '普通', '悪い'][SleepRecord.morning_conditions[record.morning_condition]] %>
          <% else %>
            未記録
          <% end %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="flex justify-center my-10 md:my-20">
    <%= link_to users_edit_path, class: "btn btn-accent px-5 rounded-full md:text-3xl md:px-5" do %>
      就寝時間と目標の起床時間を設定
    <% end %>
  </div>
</div>
</div>