config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  post '/callback' => 'linebot#callback'
  post '/send_line_message', to: 'linebot#send_message'

  get '/users', to: 'users#show', as: 'users'
  get '/users/edit', to: 'users#edit', as: 'users_edit'
  get 'recommend_routines', to: 'users#recommend_routine'

  post 'routines', to: 'routines#index'

  resources :users, only: %i[new create update]
  resources :routines, only: %i[index show]
  resources :sleep_records, only: %i[index new create]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_routines, dependent: :destroy
  has_many :routines, through: :user_routines
  has_many :sleep_records, dependent: :destroy
  belongs_to :sleep_issue, optional: true

  validates :line_user_id, presence: true, uniqueness: true

  # 就寝時間とrecommend_timeに基づいて、推奨実践時間を計算
  def calculate_time(bedtime, recommend_time)
    offset = case recommend_time
             when :before0 then 0
             when :before1 then 1 * 60 * 60
             when :before1_5 then 1.5 * 60 * 60
             when :before3 then 3 * 60 * 60
             when :before10 then 10 * 60 * 60
             else 0
             end
    (bedtime - offset).strftime('%H:%M')
  end

  def register_routine(received_text)
    routine = Routine.find_by(line_text: received_text)
    return { status: :existing_routine, name: routine.name } if existing_routine?(routine)

    create_user_routine(routine)
    create_sleep_record

    return { status: :no_bedtime, name: routine.name } if bedtime.nil?

    recommend_time = calculate_time(bedtime, routine.recommend_time.to_sym)
    { status: :success, recommend_time: recommend_time, name: routine.name }
  end

  def routines_based_on_issue
    return Routine.all if sleep_issue_id == 1

    if sleep_issue_id
      sleep_issue = SleepIssue.find_by(id: sleep_issue_id)
      sleep_issue ? sleep_issue.routines : Routine.none
    else
      Routine.all
    end
  end

  def update_issue_type(issue_type)
    sleep_issue = SleepIssue.find_by(issue_type: SleepIssue.issue_types[issue_type])
    update!(sleep_issue_id: sleep_issue.id) if sleep_issue
  end

  def current_issue_type(params_issue_type)
    params_issue_type.presence || sleep_issue&.issue_type
  end

  def selected_issue_point
    return unless sleep_issue.present?

    issue_type = sleep_issue.issue_type
    SleepIssue::ISSUE_POINTS[issue_type.to_sym]
  end

  # ユーザーのルーティンと調子を組み合わせて取得するメソッド
  def routine_and_condition_data(start_date, end_date)
    # 期間内の UserRoutine のデータを取得
    user_routines = UserRoutine.includes(:routine)
                               .where(user_id: id, choose_date: start_date..end_date)
                               .group_by { |ur| ur.choose_date + 1.day }

    # 期間内の SleepRecord のデータを取得
    sleep_records = SleepRecord.where(user_id: id, record_date: start_date + 1.day..end_date + 1.day)

    sleep_records.map do |record|
      {
        date: record.record_date,
        condition: record.morning_condition,
        routines: user_routines[record.record_date]&.map(&:routine) || []
      }
    end
  end

  def update_routine_scores
    # ルーティーンの初期スコアを0に設定
    scores = Routine.all.each_with_object({}) { |routine, hash| hash[routine.id] = 0 }

    # 最近のルーティーンと調子を取得
    recent_data = routine_and_condition_data(Date.today - 30, Date.today)

    # ルーティーンごとにスコアを計算
    recent_data.each do |data|
      data[:routines].each do |routine|
        case data[:condition]
        when 'good'
          scores[routine.id] += 1
        when 'bad'
          scores[routine.id] -= 1
        end
      end
    end
    scores
  end

  def self.today_routine
    joins(:user_routines)
      .where(user_routines: { choose_date: [Date.today, Date.yesterday] })
      .where.not(bedtime: nil)
      .distinct
  end
  

  def recommend_routines
    scores = update_routine_scores
    valid_recommend_times = %w[before0 before1 before3]
    recommendations = setup_recommendations(valid_recommend_times)

    # ルーティーンの分類
    classify_routines(scores, valid_recommend_times, recommendations)

    # 評価に基づくルーティーンの選択
    select_routines_by_score(recommendations)
  end

  private

  def setup_recommendations(valid_recommend_times)
    valid_recommend_times.each_with_object({}) { |time, hash| hash[time] = [] }
  end

  def classify_routines(scores, valid_recommend_times, recommendations)
    Routine.all.each do |routine|
      recommend_time = routine.recommend_time == 'before10' ? 'before3' : routine.recommend_time
      next unless valid_recommend_times.include?(recommend_time)

      recommendations[recommend_time] << { routine: routine, score: scores[routine.id] }
    end
  end

  def select_routines_by_score(recommendations)
    mid_recommendations = {}

    recommendations.each do |time, routines|
      top_routine = select_top_routine(routines)
      recommendations[time] = top_routine ? [top_routine[:routine]] : []

      mid_routines = select_mid_routines(routines, top_routine)
      mid_recommendations["mid_#{time}"] = mid_routines.map { |r| r[:routine] }
    end

    { top: recommendations, mid: mid_recommendations }
  end

  def select_top_routine(routines)
    routines.select { |r| r[:score] >= 1 }.max_by { |r| r[:score] }
  end

  def select_mid_routines(routines, top_routine)
    routines.select { |r| r[:score] >= 0 && (!top_routine || top_routine[:routine] != r[:routine]) }
            .sample(2)
  end

  def existing_routine?(routine)
    UserRoutine.exists?(user_id: id, routine_id: routine.id, choose_date: Date.today)
  end

  def create_user_routine(routine)
    UserRoutine.find_or_create_by(
      user_id: id,
      routine_id: routine.id,
      choose_date: Date.today
    )
  end

  def create_sleep_record
    SleepRecord.find_or_create_by(
      user_id: id,
      record_date: Date.tomorrow,
      morning_condition: nil
    )
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  require 'net/http'
  require 'uri'
  before_action :require_login, only: %i[show routine_records recommend_routines]

  def new
    redirect_to root_path if current_user
  end

  def show
    @user = User.find(session[:user_id])
    @total_routine_count = @user.user_routines.count
    @total_date_count = @user.sleep_records.count

    set_year_and_month
    @grouped_user_routines = UserRoutine.grouped_by_date(@year, @month, current_user.id)
    @grouped_sleep_records = SleepRecord.grouped_by_date(@year, @month, current_user.id)
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @user.update!(user_params)
    flash[:success] = '就寝時間と起床時間を登録しました'
    redirect_to sleep_records_path
  end

  def create
    id_token = params[:idToken]
    channel_id = ENV['CHANNEL_ID']
    res = Net::HTTP.post_form(URI.parse('https://api.line.me/oauth2/v2.1/verify'),
                              { 'id_token' => id_token, 'client_id' => channel_id })
    line_user_id = JSON.parse(res.body)['sub']
    user = User.find_by(line_user_id: line_user_id)
    user = User.create(line_user_id: line_user_id) if user.nil?
    session[:user_id] = user.id
    render json: user
  end

  def recommend_routine
    @user = current_user
    @recommendations = @user.recommend_routines
    @time_titles = {
      'before0' => '就寝直前のルーティーン',
      'before1' => '就寝1時間前のルーティーン',
      'before3' => '就寝3時間以上前のルーティーン'
    }
  end

  private

  def user_params
    params.require(:user).permit(:bedtime, :notification_time)
  end

  def set_year_and_month
    if params['month(1i)'].present? && params['month(2i)'].present?
      @year = params['month(1i)'].to_i
      @month = params['month(2i)'].to_i
    else
      @year = Date.today.year
      @month = Date.today.month
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mx-auto p-4 flex flex-col items-center mb-20">
  <h1 class="text-4xl text-black my-5">睡眠時間の設定</h1>
  <%= form_with(model: @user, local: true, class: 'bg-white mt-5 p-4 rounded shadow w-full md:w-1/2') do |form| %>
    <%= render 'shared/error_messages', object: form.object %>
    <div class="my-10 flex flex-col items-center">
    <%= form.label :bedtime, '就寝時間', class: 'block text-lg font-medium text-gray-600' %>
    <%= form.time_field :bedtime, value: @user.bedtime&.strftime("%H:%M") || '00:00', class: 'mt-1 p-3 w-3/4 border rounded-md text-lg' %>
  </div>
  <div class="mb-10 flex flex-col items-center">
    <%= form.label :notification_time, '起床時間', class: 'block text-lg font-medium text-gray-600' %>
    <%= form.time_field :notification_time, value: @user.notification_time&.strftime("%H:%M") || '07:00', class: 'mt-1 p-3 w-3/4 border rounded-md text-lg' %>
  </div>
    <div class="flex justify-center">
      <%= form.submit '保存', class: 'btn btn-primary text-lg py-2 px-4' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="flex justify-center items-center h-screen">
  <div class="flex items-center space-x-4">
    <div class="loading loading-spinner"></div>
    <p class="text-center text-3xl text-gray-700 my-20">読み込んでいます...</p>
  </div>
</div>

app/views/users/recommend_routine.html.erb
<div class="container mx-auto p-10 text-black">
  <h1 class="text-center text-3xl font-bold mb-6">あなたにおすすめのルーティーン</h1>

  <% if @recommendations[:top].values.any?(&:present?) %>
    <div class="text-center text-xl grid lg:grid-cols-3 gap-4">
      <% @recommendations[:top].each do |time, routines| %>
        <% next if routines.empty? %>
        <div>
          <h2 class="font-semibold mb-2"><%= @time_titles[time] %></h2>
          <% routines.each do |routine| %>
            <div class="card border border-black mb-5">
              <%= link_to routine_path(routine), data: { turbo: "false" } do %>
                <div class="card-body">
                  <h3 class="card-title"><%= routine.name %></h3>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-center text-xl font-bold mt-10">翌朝の調子が良かった日に実践したルーティーンをご提案します！現在ではまだ記録がないようです。</p>
    <p class="text-center text-xl font-bold mt-5">様々なルーティーンを試してみて、自分に合うものを探してみてください！</p>
  <% end %>

  <p class="text-2xl font-bold my-20 text-center">下記のルーティーンも実践をご検討ください！</p>
  <div class="text-center text-xl grid lg:grid-cols-3 gap-4">
    <% @recommendations[:mid].each do |time_key, routines| %>
      <% next if routines.empty? %>
      <% time = time_key.to_s.gsub('mid_', '') %>
      <% title = @time_titles[time] || 'ルーティーン' %>
      <div>
        <h2 class="font-semibold mb-2"><%= title %></h2>
        <% routines.each do |routine| %>
          <div class="card border border-black mb-5">
            <%= link_to routine_path(routine), data: { turbo: "false" } do %>
              <div class="card-body">
                <h3 class="card-title"><%= routine.name %></h3>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<section class="text-black">
  <div class="container px-5 pt-15 mx-auto flex flex-wrap items-center">
    <div class="w-full mb-20">
      <h1 class="title-font text-center font-medium text-4xl">ユーザーページ</h1>
    </div>

    <div class="stats bg-accent w-full flex flex-col md:flex-row">
      <div class="stat place-items-center text-white flex-grow">
        <div class="stat-title text-xl text-black">ルーティーンを実施した回数</div>
        <div class="stat-value text-black"><%= @total_routine_count %>回</div>
      </div>
      
      <div class="stat place-items-center flex-grow">
        <div class="stat-title text-xl text-black">ルーティーンを実施した日数</div>
        <div class="stat-value text-black"><%= @total_date_count %>日</div>
      </div>
    </div>
  </div>

  <div class="flex justify-center mt-15">
  <%= link_to "あなたにおすすめのルーティーンはこちら", recommend_routines_path, class: "btn btn-primary text-xl" %>
  </div>

  <div class="text-black body-font overflow-hidden mb-20">
  <h1 class='py-3 my-10 text-4xl text-center'>登録したルーティーン一覧</h1>
  <%= form_with url: users_path, method: :get, local: true, class: "text-center mb-10" do |f| %>
    <%= f.date_select :month, { discard_day: true, selected: Date.new(@year, @month, 1) }, class: "border border-black bg-white text-2xl" %>
    <%= f.submit "フィルター", class: "btn btn-primary ml-10" %>
  <% end %>
  <% if @grouped_user_routines.present? %>
  
  <div class="container mx-auto py-4">
    <% @grouped_user_routines.each do |date, routines| %>
      <div class="mb-8">
        <div class="flex items-start">
          <div class="w-1/4">
            <div class="font-semibold text-gray-700 text-2xl mb-2"><%= date %></div>
            <div>
            <% if @grouped_sleep_records[date]&.first&.morning_condition %>
              <span class="text-gray-700">翌朝のコンディション: <br><span class="font-bold"><%= ['良い', '普通', '悪い'][SleepRecord.morning_conditions[@grouped_sleep_records[date].first.morning_condition]] %></span></span>
            <% else %>
              <span class="text-gray-700">翌朝のコンディション: <br><span class="font-bold">記録なし</span></span>
            <% end %>
          </div>
          </div>
          <div class="flex flex-wrap w-3/4">
          <% routines.each do |user_routine| %>
            <%= link_to routine_path(user_routine.routine), data: { turbo: "false" }, class: "card border border-black md:w-1/4 w-full m-2" do %>
              <div class="card-body">
                <h2 class="card-title text-lg"><%= user_routine.routine.name %></h2>
              </div>
            <% end %>
          <% end %>
        </div>
        
        </div>
        <hr class="my-4">
      </div>
    <% end %>
  </div>
  <% else %>
    <p class="text-center text-2xl my-20">ルーティーンが登録されていません。</p>
  <div class="flex justify-center">
    <% if current_user.user_routines.nil? %>
      <p>まずはルーティーン一覧からルーティーンを登録してみましょう！</p>
      <%= link_to 'ルーティーン一覧を見てみる', routines_path, class: "btn btn-info mb-50 text-2xl" %>
    <% end %>
  </div>
  <% end %>
  </div>
</section>