config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  post '/callback' => 'linebot#callback'
  post '/send_line_message', to: 'linebot#send_message'

  get '/users', to: 'users#show', as: 'users'
  get '/users/edit', to: 'users#edit', as: 'users_edit'
  get 'recommend_routines', to: 'users#recommend_routine'

  post 'routines', to: 'routines#index'

  resources :users, only: %i[new create update]
  resources :routines, only: %i[index show]
  resources :sleep_records, only: %i[index new create]
end

app/views/shared/_before_login_header.html.erb
<div class="py-5 navbar bg-indigo-700 sticky top-0">
  <%= link_to root_path, data: { turbo: false }, class: 'flex items-center' do %>
    <%= image_tag 'logo.png', class: 'h-12 mr-3 rounded-full mr-1' %>
    <span class="self-center text-2xl font-bold text-cyan-400 md:inline">ZzzCrafter</span>
  <% end %>

  <div class="flex-grow"></div>

  <!-- レスポンシブ対応のためのドロップダウンメニュー -->
  <div class="md:hidden dropdown dropdown-end">
    <label tabindex="0" class="btn btn-outline btn-info text-xl">Menu</label>
    <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
      <li><%= link_to 'ルーティーン一覧', routines_path, data: { turbo: false } %></li>
      <li><%= link_to 'ログイン', new_user_path, data: { turbo: false } %></li>
    </ul>
  </div>

  <!-- デスクトップ用のメニュー -->
  <div class="hidden md:flex">
    <%= link_to 'ルーティーン一覧', routines_path, class: 'btn btn-outline btn-info text-xl mr-4' %>
    <%= link_to 'ログイン', new_user_path, data: { turbo: false }, class: 'btn btn-outline btn-info text-xl' %>
  </div>
</div>

</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_classname(message_type) %> p-4 rounded"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-indigo-700">
  <div class="container px-10 py-5 mx-auto flex flex-col items-center text-black">
    <div class="flex flex-col md:flex-row justify-center w-full text-center">
      <span class="inline-flex flex-col md:flex-row justify-center w-full md:w-auto">
        <%= link_to "利用規約", terms_of_service_path, class: 'btn btn-outline btn-info my-2 md:my-2 sm:my-5 text-center' %>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: 'btn btn-outline btn-info my-2 md:mx-8 text-center' %>
        <%= link_to "お問い合わせ", "https://forms.gle/g8w9bZhhNxfT9WzU9", class: 'btn btn-outline btn-info my-2 md:mr-4 text-center' %>
      </span>
    </div>
    <p class="text-sm mt-5">© 2024 ZzzCrafter </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="py-5 navbar bg-indigo-700 sticky top-0">
  <%= link_to root_path, data: { turbo: false }, class: 'flex items-center' do %>
    <%= image_tag 'logo.png', class: 'h-12 mr-3 rounded-full mr-1' %>
    <span class="self-center text-2xl font-bold text-cyan-400 md:inline">ZzzCrafter</span>
  <% end %>

  <div class="flex-grow"></div>

  <!-- レスポンシブ対応のためのドロップダウンメニュー -->
  <div class="md:hidden dropdown dropdown-end">
    <label tabindex="0" class="btn btn-outline btn-info text-xl">Menu</label>
    <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
      <li><%= link_to '睡眠の記録', sleep_records_path %></li>
      <li><%= link_to 'ルーティーン一覧', routines_path, data: { turbo: false } %></li>
      <li><%= link_to 'ユーザーページ', users_path %></li>
    </ul>
  </div>

  <!-- デスクトップ用のメニュー -->
  <div class="hidden md:flex">
    <%= link_to '睡眠の記録', sleep_records_path, class: 'btn btn-outline btn-info text-xl mr-4' %>
    <%= link_to 'ルーティーン一覧', routines_path, class: 'btn btn-outline btn-info text-xl mr-4' %>
    <%= link_to 'ユーザーページ', users_path, class: 'btn btn-outline btn-info text-xl' %>
  </div>
</div>